core/urls.py
from django.urls import path
from . import views
from .views import SupportListView,CarDetailView,IndexListView

app_name = 'core'

urlpatterns = [
    # path("", CarListView.as_view(), name="offers"),
    
    # path("",views.index,name='index'),
    
    path("", IndexListView.as_view(), name="index"),
    
    # path("search/", SearchListView.as_view(), name="index_search"),
    
    path("offers/", views.car_list, name='offers'),
    
    path('offers/<slug:category_slug>',views.car_list,name='offer_category'),
    
    
    path("search/", views.search,name="index_search"),
    
    path("car/", views.car,name="car"),   
    path('car/<slug:category_slug>',views.car,name='car_category'),
    
       
       
    path("offers/<slug:slug>/", CarDetailView.as_view(), name="offers_detail"),
    
    path("support/", SupportListView.as_view(), name="support"),
    
]

turbohub/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('core.urls', namespace='core')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, documet_root = settings.STATIC_ROOT)

core/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils.safestring import mark_safe
from django.urls import reverse


# Create your models here.



class Car(models.Model):
    #relation
    categories = models.ForeignKey('CarCategory',on_delete=models.CASCADE,blank=True,null=True,related_name='car_categories')
    category = models.ForeignKey('ConditionCategory',on_delete=models.CASCADE,blank=True,null=True,related_name='condition_categories')
    
    name = models.CharField(max_length=200,blank=True,null=True)
    price = models.CharField(max_length=200,blank=True,null=True)
    mileage = models.CharField(max_length=200,blank=True,null=True)
    car_image = models.ImageField(upload_to='media')
    condition = models.CharField(max_length=200,blank=True,null=True)
    brend = models.CharField(max_length=100)
    dealer_comments = models.CharField(max_length=300)
    slug = models.CharField(max_length=300, verbose_name='Slug', unique=True, blank=True, null=True)
    kilometres = models.CharField(max_length=60)
    colour = models.CharField(max_length=100)
    transmission = models.CharField(max_length=100)
    fuel_type = models.CharField(max_length=100)
    body = models.CharField(max_length=100)
    engine = models.CharField(max_length=100)
    drive_type = models.CharField(max_length=100)
    
    in_depth_specifications1 = RichTextUploadingField()
    in_depth_specifications2 = RichTextUploadingField()
    
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("core:offers_detail", kwargs={
            "slug": self.slug
        })

    
    class Meta:
        verbose_name_plural = 'Cars'
                
        
    def image_tag(self):
        return mark_safe('<img src="{}" height="100" width="100"/>'.format(self.car_image.url))
    
    
class ConditionCategory(models.Model):
    name = models.CharField(max_length=100,db_index=True)
    slug = models.SlugField(unique=True)
    
    
    
    def __str__(self):
        return self.name
 
    def get_absolute_url(self):
        return reverse('core:offer_category', args=[self.slug,])
    
    
    class Meta:
        verbose_name_plural = 'ConditionCategories'    


    
class CarCategory(models.Model):
    name = models.CharField(max_length=100,db_index=True)
    slug = models.SlugField(unique=True)
    image=models.ImageField(upload_to='media')
    
    
     


    def get_absolute_url(self):
        return reverse('core:car_category', args=[self.slug,])
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = 'CarCategories'
    




    



class Address(models.Model):
    address = models.CharField(max_length=200,blank=True,null=True)
    phone_number = models.CharField(max_length=200,default='(123) 456-7890')
    working_hours = RichTextUploadingField()
    call_us = models.CharField(max_length=200,default='+1 (289) 788-9196')
     
    
    
    def __str__(self):
        return self.address
    

class About(models.Model):
    content = RichTextUploadingField()
    
    
class Image(models.Model):
    cars_image = models.ForeignKey(Car,on_delete=models.CASCADE,blank=True,null=True,related_name='cars_image')
    image = models.ImageField(upload_to='images')
    

    def image_tag(self):
        return mark_safe('<img src="{}" height="100" width="100"/>'.format(self.image.url))
    image_tag.short_description = 'Image'
    
    

core/views.py
from unicodedata import category
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormView
from .models import About, Car,Address, CarCategory,ConditionCategory
from django.core.paginator import EmptyPage,PageNotAnInteger, Paginator



class IndexListView(ListView):
    model = Car
    template_name='index.html'
    
    
        # if 'category_slug' in self.kwargs:
        #     return super().get_queryset().filter(
        #         category_slug=self.kwargs['category_slug']
        #     )
        # else:
        #     return super().get_queryset().filter(
        #         name__icontains=self.request.GET.get('name')
        #     )
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        context["cars_list"] = Car.objects.all()[:6]
        
        context["categories"] = ConditionCategory.objects.all()
        context["categories_list"] = CarCategory.objects.all()
        
        
        return context





def car(request,category_slug=None):
    category=None
    car = []
    
    
    categories_list = CarCategory.objects.all()
    
    
    
    if category_slug:
        car=Car.objects.all()
        category=get_object_or_404(CarCategory,slug=category_slug)
        car=Car.objects.filter(categories=category)
    
    
    
    

        
    
        
    context = {
        'car':car,
        'categories_list':categories_list,
    }
        
    
    
        
    
    
    
    
    return render(request,'car.html',context)



def car_list(request,category_slug=None):
    category=None
    c = Car.objects.all().count()
    categories=ConditionCategory.objects.all()
   
    car=Car.objects.all()
    page = request.GET.get('page')
    
    paginator = Paginator(car,6)
    
    
    try:
        car = paginator.page(page)
    except EmptyPage:
        car = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        car = paginator.page(1)
    
    
    
    
    if category_slug:
        car=Car.objects.all()
        category=get_object_or_404(ConditionCategory,slug=category_slug)
        car=car.filter(category=category)
        page = request.GET.get('page')
    
        paginator = Paginator(car,6)
    
    
        try:
            car = paginator.page(page)
        except EmptyPage:
            car = paginator.page(paginator.num_pages)
        except PageNotAnInteger:
            car = paginator.page(1)
        
            
            
    return render(request,'offers.html',{
                    'categories':categories,
                    'car':car,
                    'cars':c,
                    'category':category
                    
                    })




def search(request,category_slug=None):
    category=None
    query=None
    category_query=None
    car=[]
    categories = ConditionCategory.objects.all()
    
    query = request.GET.get('search')
    
    category_query = request.GET.get('category')
    
    
    if query != '' or query is not None:
        car = Car.objects.filter(name__icontains=query)
    
    
    if category_query != '' or  category_query is not None:
        car = Car.objects.filter(category__name__icontains=category_query)
     
        if query != '' or query is None:
            car = car.filter(name__icontains=query)
            
                
                
            
            print('sdsdsbd')
               
                 
        
        
    
        
    
    context = {
        'car':car,
        'categories':categories,
        'query':query,
        'category_query':category_query,
        'category':category
        
        
    }
    
    return render(request,'result.html', context)
                                          

    
# class SearchListView(ListView):
#     template_name = 'result.html'
#     model = Car
    
#     def get_queryset(self):
#         if 'category_slug' in self.kwargs:
#             return super().get_queryset().filter(
#                 slug=self.kwargs['category_slug']
#             )
#         else:
#             return super().get_queryset().filter(
#                 name__icontains=self.request.GET.get('search','')
#             )
            
#     def get_context_data(self, **kwargs):
#         context = super(SearchListView,self).get_context_data(**kwargs)
#         query = self.request.GET.get('search','')

#         context['queryset'] = Car.objects.all().filter(name__icontains=query)
        
        
        
        
#         return context
        
        
    
        
    



        
    

# class CarListView(ListView):
#     model = Car
#     template_name = 'offers.html'
#     context_object_name = 'car_list'
    
#     paginate_by = 3
    
    
    
    
#     def get_context_data(self, request,category_slug=None,**kwargs):
#         context = super().get_context_data(**kwargs)
        
#         category=None
#         categories=ConditionCategory.objects.all()
#         car=Car.objects.all()
        
        
#         page = self.request.GET.get('page')
#         paginator = Paginator(condition,self.paginate_by)
        
        
#         try:
#             car = paginator.page(page)
#         except EmptyPage:
#             car = paginator.page(paginator.num_pages)
#         except PageNotAnInteger:
#             page = 1
#             car = paginator.page(page)
#         except:
#             car = paginator.page(self.paginate_by)
            
            
#         if category_slug:
#         category=get_object_or_404(ConditionCategory,slug=category_slug)
#         car=car.filter(category=category)
        
#         page=request.GET.get('page')
        
        
        
#         if category_slug:
#             category=get_object_or_404(ConditionCategory,slug=category_slug)
#             car=car.filter(category=category)
            
#             page = self.request.GET.get('page')
#             paginator = Paginator(car,self.paginate_by)
        
        
#             try:
#                 car = paginator.page(page)
#             except EmptyPage:
#                 car = paginator.page(paginator.num_pages)
#             except PageNotAnInteger:
#                 page = 1
#                 car = paginator.page(page)
#             else:
#                 condition = Car.get_condition_all()
        
        
#         context["categories"] = categories
#         context['car'] = car
        

            

#         return context


            
    
    

class SupportListView(ListView):
    model = Address
    template_name = 'support.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["about_list"] = About.objects.all()
        return context
    
    
class CarDetailView(DetailView):
    model = Car
    template_name = 'offers_detail.html'
    success_url = reverse_lazy("core:offers")
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["address_list"] = Address.objects.all()
        return context
    
    


    

    
    
    
    
    
    
    
    

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">

    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css">

    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.green.min.css">


    

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <title>Turbohub</title>

</head>
<body>

    {% include 'include/header.html' %}

    {% block content %}
    
    
    
    
    {% endblock content %}
    
    {% include 'include/footer.html' %}
    

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js" ></script>

    {% block js %}
    
    {% endblock js %}
    

    <script src="{% static 'js/select.js' %}"></script>
    <script src="{% static 'js/carousel.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
   

    
<script>
    const thumbs=document.querySelector(".thumb-img").children;

        function changeImage(event){
        document.querySelector(".pro-img").src=event.children[0].src
        
        for(let i=0; i<thumbs.length;i++){
          thumbs[i].classList.add("active");    
        }
        event.classList.add("active");
        }

        
        
</script> 

</body>
</html>

core/templates/car.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<section>
    <div class="my-container">
        <div class="filter-height result">
            {% if query %}
            <h3>{% with car.count as total_car %}</h3>
            
            <div class="sale "><span>{{total_car}} total</span>  cars for sale</div>
            {% endwith %}
            {% else %}
            <h3>{% with car.count as total_car %}</h3>
            
                <div class="sale "><span>{{total_car}} total</span>  cars for sale</div>
            {% endwith %}
            {% endif %}
        </div> 
    </div>
</section>
<section class="show-result gray">
    <div class="wrapper_right gray">
        <div class="my-container">
            <div class="items allteam ">
                <div class="all-cars">
                    {% for c in car %}
                    
                    
                    <a href="{{c.get_absolute_url}}">
                        <div class="item" class="width100">
                            <div class="car-img-box">
                                <img src="{{c.car_image.url}}">
                            </div>
                            <div class="details">
                                <div class="content">
                                    <h4>{{c.name}}</h4>
                                    <div class="card-details">
                                        <div class="price">
                                            {{c.price}}
                                        </div>
                                        <div class="line-2"></div>
                                        <div class="km">
                                            {{c.mileage}}
                                            
                                        </div>
                                    </div>
                                </div>
                             </div>
                        </div>
                    </a>
                    {% empty %}
                    <div class="my-container">
                        <div class="search-result">
                            <div class="about">
                                <div class="about-content">
                                    <div class="mission">SEARCH RESULT</div>
                                    {% if query is None %}
                                    <h3>{% with car.count as total_car %}</h3>
                                    
                                    {% comment %} <div class="sale "><span>{{total_car}}</span></div> {% endcomment %}
                                    {% endwith %}
                                    {% endif %}
                                    <h1>We couldn’t find any result</h1>
                                </div>
                            </div> 
            
                            <div class="search-icon">
                                <div class="lupa">
                                    <img src="{% static 'img/output-onlinegiftools.gif' %}" alt="">
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
          </div>   
        </div>
    </div>
   

</section>


{% endblock %}

core/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}


{% block content %}

<section class="main-car-slider">
    <div class="my-container my-container-w">
        
        <div class="product">
            <div class="thumb-img slider d-block">
                {% for s in categories_list %}
                <a href="{{s.get_absolute_url}}">
                <div class="box" onmouseover="changeImage(this)" onmouseout="changesImage(this)">
                    
                    <img src="{{s.image.url}}" width="200" height="300" />
                

                    {{s.name}}
                </div>
                </a>
                
                {% endfor %}
            </div>

            <div class="thumb-img slider d-none">
                {% for s in categories_list %}

                <a href="{{s.get_absolute_url}}">

                   <div class="box active d1" onclick="changeImage(this)">
                        {{s.name}}
                    </div>
                </a> 
                {% endfor %}

                
            </div>
        
             <div class="main-img">
                <div class="red-zone">
                    <img src="{% static 'img/mercedes.png' %}" class="pro-img  car d1 d2" alt="product" />
                    <img class="bg" src="{% static 'img/bg.png' %}" alt="">


                    {% comment %} <div class="button-foward">
                             <a>
                        
                            <button type="sumbit" class="more btn btn-red btn-animate">MORE DETAIL</button>
                        </a>
                    </div> {% endcomment %}
                    
                 </div> 
                             
             </div>
             
         </div>
    </div>

</section>

    <section class="search-section">
        <div class="my-container">
            <div class="search-width">
                <form action="{% url 'core:index_search' %}" method="GET" accept-charset="utf-8">
                    <div class="search-box">
                        <div class="search">
                            <img src="{% static 'svg/search.svg' %}" alt="">
                            <input type="search" name="search" placeholder="Search by Make, Model">
                        </div>
            
                        <div class="selected">
                            <div class="line"></div>
            
                            <div class="custom-select"> 
                                <select name="category">
                                    <option value="">Select Condition</option>
                                    {% for e in categories %}
                                    
                                  <option value="{{e.name}}">{{e.name}}</option>


                                  {% endfor %}
                                    
                                </select>
                            </div>
                        </div>
            
                        <div class="search-button">
                            <button type="submit">Search</button>
                        </div>
                    </div>
                </form>
                
            </div>
        </div>
    </section>


    <section class="recommended gray">
        <div class="main-slide">
            <div class="recommended-title">
                <h1>Recommended Cars</h1>
                <p>Cars we think you'll like</p>
            </div>

            <div class="slide-container">
                <div class="owl-carousel second-slide owl-theme">
                    {% for c in cars_list %}
                    <div class="item" class="width100">
                        <a href="{{c.get_absolute_url}}">
                            <div class="car-img-box">
                                <img src="{{c.car_image.url}}">
                            </div>
                        </a>
                            <div class="details">
                                <div class="content">
                                    <h4>{{c.name}}</h4>
                                    <div class="card-details">
                                        <div class="price">
                                            {{c.price}}
                                        </div>
                                        <div class="line-2"></div>
                                        <div class="km">
                                            {{c.mileage}}
                                        </div>
                                    </div>
                                </div>
                             </div>
                        </div>

                    {% endfor %}

                    
          
                </div>
            </div> 
        </div>

        <div class="view">
            <a href="{% url 'core:offers' %}">VIEW ALL OFFERS</a>
        </div>
  
    </section>


    <section class="why-choose-us-section">
        <div class="my-container">
            <div class="choose-us">
                <div class="choose-title">
                    <h1>Why Choose Us</h1>
                    <p>Here’s why lots of clients choose our services.</p>
                </div>

                <div class="choose-content">
                    <div class="reason-box">
                        <img src="{% static 'svg/Checklist.svg' %}" alt="">
                        <h4>Regular Cheks</h4>
                        <p>All our cars are regularly inspected to offer you the best options for solving the daily transportation tasks as efficiently as possible.</p>
                    </div>

                    <div class="reason-box">
                        <img src="{% static 'svg/Help.svg' %}" alt="">
                        <h4>24/7 Support</h4>
                        <p>Our team is always ready to help you 24/7 professional support with registering your vehicle and getting to know it better.</p>
                    </div>

                    <div class="reason-box">
                        <img src="{% static 'svg/idCard.svg' %}" alt="">
                        <h4>Professionalism</h4>
                        <p>Turbohub’s team has a lot of dedicated experts that are determined to give you a car that fits your needs the most.</p>
                    </div>

                    <div class="reason-box">
                        <img src="{% static 'svg/target.svg' %}" alt="">
                        <h4>Affordability</h4>
                        <p>If you are looking for an affordable way to buy a desired car, Turbohub can provide you with what you need in no time.</p>
                    </div>
                </div>
                
            </div>
        </div>
    </section>

 
{% endblock content %}

core/templates/offers.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <section class="team" id="team" name="category_query">
        <div class="team-content">
            <div class="wrapper">
                
                <div class="wrapper_left category">
                    <div class="my-container">
                        <div class="wrapper-top">

                            <div class="sale"> <span>{{cars}}</span>  cars for sale</div>

                            <ul>
                                <div class="condition">Condition:</div>
                                <li data-li="allteam" {% if not category %}class="active"{% endif %}>
                                <a href="{% url 'core:offers' %}">
                                        <p>All</p>
                                    </a>
                                </li>
                                        
                            
                                {% for x in categories %}
                            
                                        <a href="{{x.get_absolute_url}}" 
                                            >
                                        <li data-li="main" class="{% if x.slug in request.path %}active{% endif %}">
                                            
                                            <p>{{x.name}}</p>
                                            
                                        </li>
                                    </a>    
                            {% endfor %}
                            </ul>
                            </div>
                    </div>
                </div>

                <div class="wrapper_right gray">
                    <div class="my-container">
                        <div class="items allteam">
                            <div class="all-cars">
                                
                                {% for e in car %}
                                <div class="item" class="width100">
                                        <a href="{{e.get_absolute_url}}">
                                            <div class="car-img-box">
                                                <img src="{{e.car_image.url}}">
                                            </div>
                                        </a>
                                        <div class="details">
                                            <div class="content">
                                                <h4>{{e.name}}</h4>
                                                <div class="card-details">
                                                    <div class="price">
                                                        {{e.price}}
                                                    </div>
                                                    <div class="line-2"></div>
                                                    <div class="km">
                                                        {{e.mileage}}
                                                        
                                                    </div>
                                                </div>
                                            </div>
                                         </div>
                                    </div>
                                {% endfor %}

                                
                            </div>
                            
                            
                            
                          
                            
                        </div>

                       
                        
                        
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="pages">
        <div class="my-container">
            <div class="page-pagination">
                <div class="pagination">
                    {% if car.has_other_pages %}
                    <ul class="pagination">
                        {% if car.has_previous %}
                        <li class="page-item btn prev disabled">
                            <a class="page-link" href="?page={{car.previous_page_number}}"><span><i class="fas fa-angle-left"></i>Previous</span></a>
                        </li>
                        {% endif %}

                        {% for i in car.paginator.page_range %}
                        {% if car.number == i %}
                        <li class="page-item first numb active" aria-current='page'>
                            <a class="page-link" href="?page={{i}}"><span>{{i}}</span></a>
                        </li>
                        {% else %}

                         
                        <li class="first numb">
                            <a class="page-link" href="?page={{i}}">{{i}}</a>
                        </li>
                        {% endif %}
                        {% endfor %}
                        
                        
                        {% if car.has_next %}
                        <li class="page-item btn next">
                            <a class="page-link" tabindex="-1" href="?page={{car.next_page_number}}"><span>Next <i class="fas fa-angle-right"></i></span></a>
                        </li>
                        {% endif %}
                        {% comment %} <li class="btn prev"><span><i class="fas fa-angle-left"></i> Previous</span></li> 
                        <li class="first numb"><span>1</span></li>
                        <li class="first numb"><span>2</span></li>
                        <li class="first numb"><span>3</span></li>
                        <li class="btn next"><span>Next <i class="fas fa-angle-right"></i></span></li> {% endcomment %}
                        <!--pages or li are comes from javascript -->
                     </ul>
                    {% endif %}
                  </div>
            </div>
           
        </div>
    </section>


    {% endblock content %} 
    

    {% block js %}
    
    <script src="{% static 'js/tab.js' %}"></script>
    <script src="{% static 'js/pagination.js' %}"></script>
    
    {% endblock js %}